# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Perl-Demo
version:      0.04
version_from: gtk-perl-demo.pl
installdirs:  site
requires:
    Gtk2:                          1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
